/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUNDinclude = 1,
  anon_sym_POUNDdefine = 2,
  anon_sym_function = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_nonpayable = 6,
  anon_sym_payable = 7,
  anon_sym_pure = 8,
  anon_sym_view = 9,
  anon_sym_returns = 10,
  aux_sym_solidity_parameter_types_token1 = 11,
  anon_sym_COLON = 12,
  sym_label_name = 13,
  anon_sym_macro = 14,
  anon_sym_EQ = 15,
  anon_sym_COMMA = 16,
  anon_sym_takes = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_dup1 = 22,
  anon_sym_add = 23,
  anon_sym_swap1 = 24,
  anon_sym_calldataload = 25,
  anon_sym_shr = 26,
  anon_sym_and = 27,
  anon_sym_jump = 28,
  anon_sym_jumpi = 29,
  anon_sym_iszero = 30,
  anon_sym_mstore = 31,
  anon_sym_revert = 32,
  sym_number = 33,
  sym_hex_literal = 34,
  sym_string = 35,
  sym_identifier = 36,
  sym_macro_name = 37,
  sym_comment = 38,
  sym_source_file = 39,
  sym__top_level_item = 40,
  sym_preprocessor = 41,
  sym_solidity_function = 42,
  sym_solidity_parameter_types = 43,
  sym_solidity_return_types = 44,
  sym_jump_label_definition = 45,
  sym_jump_label_reference = 46,
  sym_macro_definition = 47,
  sym_parameter_list = 48,
  sym_parameters = 49,
  sym_takes_clause = 50,
  sym_returns_clause = 51,
  sym_parameter_usage = 52,
  sym_parameter = 53,
  sym_macro_call = 54,
  sym_arguments = 55,
  sym_argument = 56,
  sym_block = 57,
  sym_opcode = 58,
  sym_literal = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_parameters_repeat1 = 61,
  aux_sym_arguments_repeat1 = 62,
  aux_sym_block_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDinclude] = "#include",
  [anon_sym_POUNDdefine] = "#define",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_nonpayable] = "nonpayable",
  [anon_sym_payable] = "payable",
  [anon_sym_pure] = "pure",
  [anon_sym_view] = "view",
  [anon_sym_returns] = "returns",
  [aux_sym_solidity_parameter_types_token1] = "solidity_parameter_types_token1",
  [anon_sym_COLON] = ":",
  [sym_label_name] = "label_name",
  [anon_sym_macro] = "macro",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_takes] = "takes",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_dup1] = "dup1",
  [anon_sym_add] = "add",
  [anon_sym_swap1] = "swap1",
  [anon_sym_calldataload] = "calldataload",
  [anon_sym_shr] = "shr",
  [anon_sym_and] = "and",
  [anon_sym_jump] = "jump",
  [anon_sym_jumpi] = "jumpi",
  [anon_sym_iszero] = "iszero",
  [anon_sym_mstore] = "mstore",
  [anon_sym_revert] = "revert",
  [sym_number] = "number",
  [sym_hex_literal] = "hex_literal",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_macro_name] = "macro_name",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__top_level_item] = "_top_level_item",
  [sym_preprocessor] = "preprocessor",
  [sym_solidity_function] = "solidity_function",
  [sym_solidity_parameter_types] = "solidity_parameter_types",
  [sym_solidity_return_types] = "solidity_return_types",
  [sym_jump_label_definition] = "jump_label_definition",
  [sym_jump_label_reference] = "jump_label_reference",
  [sym_macro_definition] = "macro_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_parameters] = "parameters",
  [sym_takes_clause] = "takes_clause",
  [sym_returns_clause] = "returns_clause",
  [sym_parameter_usage] = "parameter_usage",
  [sym_parameter] = "parameter",
  [sym_macro_call] = "macro_call",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_block] = "block",
  [sym_opcode] = "opcode",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [anon_sym_POUNDdefine] = anon_sym_POUNDdefine,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_nonpayable] = anon_sym_nonpayable,
  [anon_sym_payable] = anon_sym_payable,
  [anon_sym_pure] = anon_sym_pure,
  [anon_sym_view] = anon_sym_view,
  [anon_sym_returns] = anon_sym_returns,
  [aux_sym_solidity_parameter_types_token1] = aux_sym_solidity_parameter_types_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_label_name] = sym_label_name,
  [anon_sym_macro] = anon_sym_macro,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_takes] = anon_sym_takes,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_dup1] = anon_sym_dup1,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_swap1] = anon_sym_swap1,
  [anon_sym_calldataload] = anon_sym_calldataload,
  [anon_sym_shr] = anon_sym_shr,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_jumpi] = anon_sym_jumpi,
  [anon_sym_iszero] = anon_sym_iszero,
  [anon_sym_mstore] = anon_sym_mstore,
  [anon_sym_revert] = anon_sym_revert,
  [sym_number] = sym_number,
  [sym_hex_literal] = sym_hex_literal,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [sym_macro_name] = sym_macro_name,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__top_level_item] = sym__top_level_item,
  [sym_preprocessor] = sym_preprocessor,
  [sym_solidity_function] = sym_solidity_function,
  [sym_solidity_parameter_types] = sym_solidity_parameter_types,
  [sym_solidity_return_types] = sym_solidity_return_types,
  [sym_jump_label_definition] = sym_jump_label_definition,
  [sym_jump_label_reference] = sym_jump_label_reference,
  [sym_macro_definition] = sym_macro_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameters] = sym_parameters,
  [sym_takes_clause] = sym_takes_clause,
  [sym_returns_clause] = sym_returns_clause,
  [sym_parameter_usage] = sym_parameter_usage,
  [sym_parameter] = sym_parameter,
  [sym_macro_call] = sym_macro_call,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym_block] = sym_block,
  [sym_opcode] = sym_opcode,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDdefine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nonpayable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_payable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_view] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_solidity_parameter_types_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_macro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_takes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dup1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swap1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_calldataload] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jumpi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iszero] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mstore] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_revert] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_item] = {
    .visible = false,
    .named = true,
  },
  [sym_preprocessor] = {
    .visible = true,
    .named = true,
  },
  [sym_solidity_function] = {
    .visible = true,
    .named = true,
  },
  [sym_solidity_parameter_types] = {
    .visible = true,
    .named = true,
  },
  [sym_solidity_return_types] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_label_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_takes_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_usage] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 2},
  [2] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 8,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 9,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 7,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 95,
  [111] = 91,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(105);
      ADVANCE_MAP(
        '"', 1,
        '#', 30,
        '(', 109,
        ')', 110,
        ',', 200,
        '/', 4,
        '0', 228,
        ':', 127,
        '<', 202,
        '=', 199,
        '>', 203,
        'a', 26,
        'c', 10,
        'd', 89,
        'f', 93,
        'i', 81,
        'j', 90,
        'm', 11,
        'n', 66,
        'p', 12,
        'r', 33,
        's', 46,
        't', 13,
        'v', 47,
        '{', 204,
        '}', 205,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(229);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(233);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(231);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(110);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(228);
      if (lookahead == '<') ADVANCE(202);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(229);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(232);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(196);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(110);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(232);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(235);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(234);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '/', 4,
        '0', 228,
        ':', 127,
        '<', 202,
        '_', 195,
        'a', 141,
        'c', 130,
        'd', 186,
        'i', 179,
        'j', 187,
        'm', 180,
        'r', 146,
        's', 155,
        '}', 205,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(229);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(233);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(206);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(210);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 's') ADVANCE(85);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(95);
      if (lookahead == 'u') ADVANCE(79);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(96);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 'b') ADVANCE(56);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(86);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(53);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(75);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(208);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(216);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(212);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(34);
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 32:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(224);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 45:
      if (lookahead == 'f') ADVANCE(48);
      END_STATE();
    case 46:
      if (lookahead == 'h') ADVANCE(74);
      if (lookahead == 'w') ADVANCE(18);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 50:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(91);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 57:
      if (lookahead == 'm') ADVANCE(71);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(198);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(222);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(80);
      END_STATE();
    case 70:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 71:
      if (lookahead == 'p') ADVANCE(218);
      END_STATE();
    case 72:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(214);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 82:
      if (lookahead == 's') ADVANCE(201);
      END_STATE();
    case 83:
      if (lookahead == 's') ADVANCE(119);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(226);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(92);
      if (lookahead == 'v') ADVANCE(44);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 89:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 90:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 91:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 93:
      if (lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 94:
      if (lookahead == 'w') ADVANCE(117);
      END_STATE();
    case 95:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 96:
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 97:
      if (lookahead == 'z') ADVANCE(43);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(230);
      END_STATE();
    case 99:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(166);
      if (lookahead == 'p') ADVANCE(131);
      if (lookahead == 'r') ADVANCE(153);
      if (lookahead == 'v') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(99);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 100:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(131);
      if (lookahead == 'r') ADVANCE(153);
      if (lookahead == 'v') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(100);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 101:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(188);
      if (lookahead == 'r') ADVANCE(153);
      if (lookahead == 'v') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(101);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 102:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(153);
      if (lookahead == 'v') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(102);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 103:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(153);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(103);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 104:
      if (eof) ADVANCE(105);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(104);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(229);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_POUNDdefine);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_nonpayable);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_nonpayable);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_payable);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_payable);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_pure);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_pure);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_view);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_view);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_returns);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == ')') ADVANCE(235);
      if (lookahead != 0) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '*') ADVANCE(122);
      if (lookahead == '/') ADVANCE(126);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '*') ADVANCE(122);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead == '*') ADVANCE(123);
      if (lookahead == '/') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '*') ADVANCE(126);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead == '/') ADVANCE(124);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(126);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_solidity_parameter_types_token1);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == '1') ADVANCE(207);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == '1') ADVANCE(211);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(192);
      if (lookahead == 'u') ADVANCE(178);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(171);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'a') ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'b') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'b') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'd') ADVANCE(142);
      if (lookahead == 'n') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'd') ADVANCE(209);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'd') ADVANCE(217);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'd') ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'd') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(190);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(225);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(191);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(175);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'e') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'h') ADVANCE(173);
      if (lookahead == 'w') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'i') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'l') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'l') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'l') ADVANCE(168);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'l') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'l') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'm') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'n') ADVANCE(181);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'n') ADVANCE(172);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'o') ADVANCE(223);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'o') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'o') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'o') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'p') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'p') ADVANCE(219);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'p') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'p') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'r') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 's') ADVANCE(194);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 's') ADVANCE(182);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 's') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 't') ADVANCE(167);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 't') ADVANCE(227);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 't') ADVANCE(189);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 't') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'u') ADVANCE(169);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'u') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'u') ADVANCE(178);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'u') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'v') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'w') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'y') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'y') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead == 'z') ADVANCE(152);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(197);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_label_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(195);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(233);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_label_name);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(232);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(196);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_label_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_macro);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_takes);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_dup1);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_dup1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_swap1);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(anon_sym_swap1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(anon_sym_calldataload);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_calldataload);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(anon_sym_shr);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(anon_sym_shr);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(anon_sym_jump);
      if (lookahead == 'i') ADVANCE(220);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(anon_sym_jump);
      if (lookahead == 'i') ADVANCE(221);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_jumpi);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(anon_sym_jumpi);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(anon_sym_iszero);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_iszero);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(anon_sym_mstore);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(anon_sym_mstore);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_revert);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(anon_sym_revert);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'x') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(229);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(229);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_hex_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(230);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(232);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_macro_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(233);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(235);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 104},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 104},
  [14] = {.lex_state = 104},
  [15] = {.lex_state = 99},
  [16] = {.lex_state = 99},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 100},
  [19] = {.lex_state = 100},
  [20] = {.lex_state = 101},
  [21] = {.lex_state = 101},
  [22] = {.lex_state = 101},
  [23] = {.lex_state = 102},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 102},
  [26] = {.lex_state = 102},
  [27] = {.lex_state = 102},
  [28] = {.lex_state = 103},
  [29] = {.lex_state = 103},
  [30] = {.lex_state = 103},
  [31] = {.lex_state = 103},
  [32] = {.lex_state = 103},
  [33] = {.lex_state = 104},
  [34] = {.lex_state = 104},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 104},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 104},
  [39] = {.lex_state = 104},
  [40] = {.lex_state = 104},
  [41] = {.lex_state = 104},
  [42] = {.lex_state = 104},
  [43] = {.lex_state = 104},
  [44] = {.lex_state = 104},
  [45] = {.lex_state = 104},
  [46] = {.lex_state = 104},
  [47] = {.lex_state = 104},
  [48] = {.lex_state = 104},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 125},
  [51] = {.lex_state = 125},
  [52] = {.lex_state = 125},
  [53] = {.lex_state = 125},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 125},
  [57] = {.lex_state = 125},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 125},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 104},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 104},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [anon_sym_POUNDdefine] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_nonpayable] = ACTIONS(1),
    [anon_sym_payable] = ACTIONS(1),
    [anon_sym_pure] = ACTIONS(1),
    [anon_sym_view] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_macro] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_takes] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_dup1] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_swap1] = ACTIONS(1),
    [anon_sym_calldataload] = ACTIONS(1),
    [anon_sym_shr] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_jumpi] = ACTIONS(1),
    [anon_sym_iszero] = ACTIONS(1),
    [anon_sym_mstore] = ACTIONS(1),
    [anon_sym_revert] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(101),
    [sym__top_level_item] = STATE(13),
    [sym_preprocessor] = STATE(13),
    [sym_solidity_function] = STATE(13),
    [sym_jump_label_definition] = STATE(13),
    [sym_macro_definition] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDinclude] = ACTIONS(7),
    [anon_sym_POUNDdefine] = ACTIONS(9),
    [sym_label_name] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      sym_label_name,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_hex_literal,
    ACTIONS(27), 1,
      sym_macro_name,
    ACTIONS(29), 1,
      sym_comment,
    STATE(3), 7,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_parameter_usage,
      sym_macro_call,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(21), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [44] = 9,
    ACTIONS(15), 1,
      sym_label_name,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_hex_literal,
    ACTIONS(27), 1,
      sym_macro_name,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      sym_comment,
    STATE(4), 7,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_parameter_usage,
      sym_macro_call,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(21), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [88] = 9,
    ACTIONS(35), 1,
      sym_label_name,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(49), 1,
      sym_hex_literal,
    ACTIONS(52), 1,
      sym_macro_name,
    ACTIONS(55), 1,
      sym_comment,
    STATE(4), 7,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_parameter_usage,
      sym_macro_call,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(43), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [132] = 3,
    ACTIONS(58), 1,
      anon_sym_COLON,
    ACTIONS(62), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(60), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [158] = 2,
    ACTIONS(66), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(64), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [181] = 2,
    ACTIONS(70), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(68), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [204] = 2,
    ACTIONS(74), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(72), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [227] = 2,
    ACTIONS(78), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(76), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [250] = 2,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(80), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [273] = 2,
    ACTIONS(86), 4,
      anon_sym_LT,
      anon_sym_RBRACE,
      sym_hex_literal,
      sym_comment,
    ACTIONS(84), 14,
      sym_label_name,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_macro_name,
  [296] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    ACTIONS(90), 1,
      sym_label_name,
    ACTIONS(92), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_number,
    ACTIONS(96), 1,
      sym_hex_literal,
    ACTIONS(98), 1,
      sym_identifier,
    STATE(55), 1,
      sym_argument,
    STATE(85), 1,
      sym_arguments,
    STATE(70), 3,
      sym_jump_label_reference,
      sym_parameter_usage,
      sym_literal,
  [329] = 6,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(9), 1,
      anon_sym_POUNDdefine,
    ACTIONS(11), 1,
      sym_label_name,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      sym_comment,
    STATE(14), 6,
      sym__top_level_item,
      sym_preprocessor,
      sym_solidity_function,
      sym_jump_label_definition,
      sym_macro_definition,
      aux_sym_source_file_repeat1,
  [353] = 6,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      anon_sym_POUNDinclude,
    ACTIONS(109), 1,
      anon_sym_POUNDdefine,
    ACTIONS(112), 1,
      sym_label_name,
    ACTIONS(115), 1,
      sym_comment,
    STATE(14), 6,
      sym__top_level_item,
      sym_preprocessor,
      sym_solidity_function,
      sym_jump_label_definition,
      sym_macro_definition,
      aux_sym_source_file_repeat1,
  [377] = 7,
    ACTIONS(120), 1,
      anon_sym_nonpayable,
    ACTIONS(122), 1,
      anon_sym_payable,
    ACTIONS(124), 1,
      anon_sym_pure,
    ACTIONS(126), 1,
      anon_sym_view,
    ACTIONS(128), 1,
      anon_sym_returns,
    ACTIONS(130), 1,
      sym_label_name,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [402] = 7,
    ACTIONS(134), 1,
      anon_sym_nonpayable,
    ACTIONS(136), 1,
      anon_sym_payable,
    ACTIONS(138), 1,
      anon_sym_pure,
    ACTIONS(140), 1,
      anon_sym_view,
    ACTIONS(142), 1,
      anon_sym_returns,
    ACTIONS(144), 1,
      sym_label_name,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [427] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_label_name,
    ACTIONS(92), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_number,
    ACTIONS(96), 1,
      sym_hex_literal,
    ACTIONS(98), 1,
      sym_identifier,
    STATE(73), 1,
      sym_argument,
    STATE(70), 3,
      sym_jump_label_reference,
      sym_parameter_usage,
      sym_literal,
  [454] = 6,
    ACTIONS(122), 1,
      anon_sym_payable,
    ACTIONS(124), 1,
      anon_sym_pure,
    ACTIONS(126), 1,
      anon_sym_view,
    ACTIONS(128), 1,
      anon_sym_returns,
    ACTIONS(130), 1,
      sym_label_name,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [476] = 6,
    ACTIONS(148), 1,
      anon_sym_payable,
    ACTIONS(150), 1,
      anon_sym_pure,
    ACTIONS(152), 1,
      anon_sym_view,
    ACTIONS(154), 1,
      anon_sym_returns,
    ACTIONS(156), 1,
      sym_label_name,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [498] = 5,
    ACTIONS(150), 1,
      anon_sym_pure,
    ACTIONS(152), 1,
      anon_sym_view,
    ACTIONS(154), 1,
      anon_sym_returns,
    ACTIONS(156), 1,
      sym_label_name,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [517] = 5,
    ACTIONS(160), 1,
      anon_sym_pure,
    ACTIONS(162), 1,
      anon_sym_view,
    ACTIONS(164), 1,
      anon_sym_returns,
    ACTIONS(166), 1,
      sym_label_name,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [536] = 5,
    ACTIONS(124), 1,
      anon_sym_pure,
    ACTIONS(126), 1,
      anon_sym_view,
    ACTIONS(128), 1,
      anon_sym_returns,
    ACTIONS(130), 1,
      sym_label_name,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [555] = 4,
    ACTIONS(152), 1,
      anon_sym_view,
    ACTIONS(154), 1,
      anon_sym_returns,
    ACTIONS(156), 1,
      sym_label_name,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [571] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_returns,
    ACTIONS(170), 1,
      anon_sym_takes,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_takes_clause,
    STATE(36), 1,
      sym_block,
    STATE(67), 1,
      sym_returns_clause,
  [593] = 4,
    ACTIONS(162), 1,
      anon_sym_view,
    ACTIONS(164), 1,
      anon_sym_returns,
    ACTIONS(166), 1,
      sym_label_name,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [609] = 4,
    ACTIONS(126), 1,
      anon_sym_view,
    ACTIONS(128), 1,
      anon_sym_returns,
    ACTIONS(130), 1,
      sym_label_name,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [625] = 4,
    ACTIONS(176), 1,
      anon_sym_view,
    ACTIONS(178), 1,
      anon_sym_returns,
    ACTIONS(180), 1,
      sym_label_name,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [641] = 3,
    ACTIONS(154), 1,
      anon_sym_returns,
    ACTIONS(156), 1,
      sym_label_name,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [654] = 3,
    ACTIONS(128), 1,
      anon_sym_returns,
    ACTIONS(130), 1,
      sym_label_name,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [667] = 3,
    ACTIONS(184), 1,
      anon_sym_returns,
    ACTIONS(186), 1,
      sym_label_name,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [680] = 3,
    ACTIONS(178), 1,
      anon_sym_returns,
    ACTIONS(180), 1,
      sym_label_name,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [693] = 3,
    ACTIONS(164), 1,
      anon_sym_returns,
    ACTIONS(166), 1,
      sym_label_name,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_comment,
  [706] = 1,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [714] = 1,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [722] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_returns,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    STATE(63), 1,
      sym_returns_clause,
  [738] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [746] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(49), 1,
      sym_parameter,
    STATE(89), 1,
      sym_parameters,
  [762] = 1,
    ACTIONS(198), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [770] = 1,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [778] = 1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [786] = 1,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [794] = 1,
    ACTIONS(204), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [802] = 1,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [810] = 1,
    ACTIONS(206), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [818] = 1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [826] = 1,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [834] = 1,
    ACTIONS(208), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [842] = 1,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_POUNDdefine,
      sym_label_name,
      sym_comment,
  [850] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_parameters_repeat1,
  [863] = 4,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    STATE(75), 1,
      sym_solidity_return_types,
  [876] = 4,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_solidity_return_types,
  [889] = 4,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 1,
      aux_sym_solidity_parameter_types_token1,
    STATE(84), 1,
      sym_solidity_parameter_types,
  [902] = 4,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_solidity_return_types,
  [915] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_parameters_repeat1,
  [928] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_arguments_repeat1,
  [941] = 4,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      sym_solidity_return_types,
  [954] = 4,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_solidity_return_types,
  [967] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_arguments_repeat1,
  [980] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_arguments_repeat1,
  [993] = 4,
    ACTIONS(218), 1,
      aux_sym_solidity_parameter_types_token1,
    ACTIONS(220), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      sym_solidity_return_types,
  [1006] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_parameters_repeat1,
  [1019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1027] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
  [1037] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
    STATE(106), 1,
      sym_parameter_list,
  [1047] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_function,
    ACTIONS(258), 1,
      anon_sym_macro,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1065] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
  [1075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 2,
      anon_sym_returns,
      anon_sym_LBRACE,
  [1083] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1107] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(71), 1,
      sym_parameter,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [1140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_EQ,
  [1147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
  [1154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [1161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LBRACE,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
  [1175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
  [1182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_macro_name,
  [1189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_LPAREN,
  [1196] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [1203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
  [1217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
  [1224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
  [1231] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
  [1245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_identifier,
  [1252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
  [1259] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_EQ,
  [1266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [1273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_GT,
  [1280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym_number,
  [1287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
  [1294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
  [1301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_COLON,
  [1315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      ts_builtin_sym_end,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_LPAREN,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_number,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_EQ,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_string,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_LPAREN,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_GT,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_identifier,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 227,
  [SMALL_STATE(10)] = 250,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 296,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 353,
  [SMALL_STATE(15)] = 377,
  [SMALL_STATE(16)] = 402,
  [SMALL_STATE(17)] = 427,
  [SMALL_STATE(18)] = 454,
  [SMALL_STATE(19)] = 476,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 517,
  [SMALL_STATE(22)] = 536,
  [SMALL_STATE(23)] = 555,
  [SMALL_STATE(24)] = 571,
  [SMALL_STATE(25)] = 593,
  [SMALL_STATE(26)] = 609,
  [SMALL_STATE(27)] = 625,
  [SMALL_STATE(28)] = 641,
  [SMALL_STATE(29)] = 654,
  [SMALL_STATE(30)] = 667,
  [SMALL_STATE(31)] = 680,
  [SMALL_STATE(32)] = 693,
  [SMALL_STATE(33)] = 706,
  [SMALL_STATE(34)] = 714,
  [SMALL_STATE(35)] = 722,
  [SMALL_STATE(36)] = 738,
  [SMALL_STATE(37)] = 746,
  [SMALL_STATE(38)] = 762,
  [SMALL_STATE(39)] = 770,
  [SMALL_STATE(40)] = 778,
  [SMALL_STATE(41)] = 786,
  [SMALL_STATE(42)] = 794,
  [SMALL_STATE(43)] = 802,
  [SMALL_STATE(44)] = 810,
  [SMALL_STATE(45)] = 818,
  [SMALL_STATE(46)] = 826,
  [SMALL_STATE(47)] = 834,
  [SMALL_STATE(48)] = 842,
  [SMALL_STATE(49)] = 850,
  [SMALL_STATE(50)] = 863,
  [SMALL_STATE(51)] = 876,
  [SMALL_STATE(52)] = 889,
  [SMALL_STATE(53)] = 902,
  [SMALL_STATE(54)] = 915,
  [SMALL_STATE(55)] = 928,
  [SMALL_STATE(56)] = 941,
  [SMALL_STATE(57)] = 954,
  [SMALL_STATE(58)] = 967,
  [SMALL_STATE(59)] = 980,
  [SMALL_STATE(60)] = 993,
  [SMALL_STATE(61)] = 1006,
  [SMALL_STATE(62)] = 1019,
  [SMALL_STATE(63)] = 1027,
  [SMALL_STATE(64)] = 1037,
  [SMALL_STATE(65)] = 1047,
  [SMALL_STATE(66)] = 1057,
  [SMALL_STATE(67)] = 1065,
  [SMALL_STATE(68)] = 1075,
  [SMALL_STATE(69)] = 1083,
  [SMALL_STATE(70)] = 1091,
  [SMALL_STATE(71)] = 1099,
  [SMALL_STATE(72)] = 1107,
  [SMALL_STATE(73)] = 1117,
  [SMALL_STATE(74)] = 1125,
  [SMALL_STATE(75)] = 1133,
  [SMALL_STATE(76)] = 1140,
  [SMALL_STATE(77)] = 1147,
  [SMALL_STATE(78)] = 1154,
  [SMALL_STATE(79)] = 1161,
  [SMALL_STATE(80)] = 1168,
  [SMALL_STATE(81)] = 1175,
  [SMALL_STATE(82)] = 1182,
  [SMALL_STATE(83)] = 1189,
  [SMALL_STATE(84)] = 1196,
  [SMALL_STATE(85)] = 1203,
  [SMALL_STATE(86)] = 1210,
  [SMALL_STATE(87)] = 1217,
  [SMALL_STATE(88)] = 1224,
  [SMALL_STATE(89)] = 1231,
  [SMALL_STATE(90)] = 1238,
  [SMALL_STATE(91)] = 1245,
  [SMALL_STATE(92)] = 1252,
  [SMALL_STATE(93)] = 1259,
  [SMALL_STATE(94)] = 1266,
  [SMALL_STATE(95)] = 1273,
  [SMALL_STATE(96)] = 1280,
  [SMALL_STATE(97)] = 1287,
  [SMALL_STATE(98)] = 1294,
  [SMALL_STATE(99)] = 1301,
  [SMALL_STATE(100)] = 1308,
  [SMALL_STATE(101)] = 1315,
  [SMALL_STATE(102)] = 1322,
  [SMALL_STATE(103)] = 1329,
  [SMALL_STATE(104)] = 1336,
  [SMALL_STATE(105)] = 1343,
  [SMALL_STATE(106)] = 1350,
  [SMALL_STATE(107)] = 1357,
  [SMALL_STATE(108)] = 1364,
  [SMALL_STATE(109)] = 1371,
  [SMALL_STATE(110)] = 1378,
  [SMALL_STATE(111)] = 1385,
  [SMALL_STATE(112)] = 1392,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_label_reference, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_label_reference, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcode, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcode, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_label_definition, 2, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_label_definition, 2, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_usage, 3, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_usage, 3, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 6, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 6, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 5, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 5, 0, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 7, 0, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 7, 0, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 8, 0, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 8, 0, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 9, 0, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 9, 0, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 10, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_function, 10, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 12, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 14, 0, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 6, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 7, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 8, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 11, 0, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_function, 13, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_takes_clause, 4, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter_types, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_clause, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_return_types, 1, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [318] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_huff(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "huff",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
