/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 15
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUNDdefine = 1,
  anon_sym_function = 2,
  anon_sym_returns = 3,
  anon_sym_event = 4,
  sym_solidity_modifier = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_memory = 9,
  anon_sym_calldata = 10,
  anon_sym_POUNDinclude = 11,
  anon_sym_LT = 12,
  anon_sym_GT = 13,
  anon_sym_macro = 14,
  anon_sym_fn = 15,
  anon_sym_EQ = 16,
  anon_sym_takes = 17,
  anon_sym_COLON = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_table = 21,
  anon_sym_jumptable = 22,
  anon_sym_jumpable__packed = 23,
  anon_sym_constant = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  anon_sym_dup1 = 27,
  anon_sym_add = 28,
  anon_sym_swap1 = 29,
  anon_sym_calldataload = 30,
  anon_sym_shr = 31,
  anon_sym_and = 32,
  anon_sym_jump = 33,
  anon_sym_jumpi = 34,
  anon_sym_iszero = 35,
  anon_sym_mstore = 36,
  anon_sym_revert = 37,
  sym_number = 38,
  sym_hex_literal = 39,
  sym_string = 40,
  sym_identifier = 41,
  sym_comment = 42,
  sym_source_file = 43,
  sym_definition = 44,
  sym_interface_function = 45,
  sym_interface_event = 46,
  sym_solidity_parameter_list = 47,
  sym_solidity_parameter = 48,
  sym_preprocessor = 49,
  sym_parameters = 50,
  sym_parameter_usage = 51,
  sym_macro_definition = 52,
  sym_macro_params = 53,
  sym_macro_call = 54,
  sym_jump_label_definition = 55,
  sym_jump_label_reference = 56,
  sym_block = 57,
  sym_table_definition = 58,
  sym_constant_definition = 59,
  sym_constant_reference = 60,
  sym_opcode = 61,
  sym_literal = 62,
  aux_sym_source_file_repeat1 = 63,
  aux_sym_interface_function_repeat1 = 64,
  aux_sym_solidity_parameter_list_repeat1 = 65,
  aux_sym_parameters_repeat1 = 66,
  aux_sym_macro_params_repeat1 = 67,
  aux_sym_block_repeat1 = 68,
  aux_sym_table_definition_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDdefine] = "#define",
  [anon_sym_function] = "function",
  [anon_sym_returns] = "returns",
  [anon_sym_event] = "event",
  [sym_solidity_modifier] = "solidity_modifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_memory] = "memory",
  [anon_sym_calldata] = "calldata",
  [anon_sym_POUNDinclude] = "#include",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_macro] = "macro",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_takes] = "takes",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_table] = "table",
  [anon_sym_jumptable] = "jumptable",
  [anon_sym_jumpable__packed] = "jumpable__packed",
  [anon_sym_constant] = "constant",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_dup1] = "dup1",
  [anon_sym_add] = "add",
  [anon_sym_swap1] = "swap1",
  [anon_sym_calldataload] = "calldataload",
  [anon_sym_shr] = "shr",
  [anon_sym_and] = "and",
  [anon_sym_jump] = "jump",
  [anon_sym_jumpi] = "jumpi",
  [anon_sym_iszero] = "iszero",
  [anon_sym_mstore] = "mstore",
  [anon_sym_revert] = "revert",
  [sym_number] = "number",
  [sym_hex_literal] = "hex_literal",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_interface_function] = "interface_function",
  [sym_interface_event] = "interface_event",
  [sym_solidity_parameter_list] = "solidity_parameter_list",
  [sym_solidity_parameter] = "solidity_parameter",
  [sym_preprocessor] = "preprocessor",
  [sym_parameters] = "parameters",
  [sym_parameter_usage] = "parameter_usage",
  [sym_macro_definition] = "macro_definition",
  [sym_macro_params] = "macro_params",
  [sym_macro_call] = "macro_call",
  [sym_jump_label_definition] = "jump_label_definition",
  [sym_jump_label_reference] = "jump_label_reference",
  [sym_block] = "block",
  [sym_table_definition] = "table_definition",
  [sym_constant_definition] = "constant_definition",
  [sym_constant_reference] = "constant_reference",
  [sym_opcode] = "opcode",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_interface_function_repeat1] = "interface_function_repeat1",
  [aux_sym_solidity_parameter_list_repeat1] = "solidity_parameter_list_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_macro_params_repeat1] = "macro_params_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_table_definition_repeat1] = "table_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDdefine] = anon_sym_POUNDdefine,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_returns] = anon_sym_returns,
  [anon_sym_event] = anon_sym_event,
  [sym_solidity_modifier] = sym_solidity_modifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_memory] = anon_sym_memory,
  [anon_sym_calldata] = anon_sym_calldata,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_macro] = anon_sym_macro,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_takes] = anon_sym_takes,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_table] = anon_sym_table,
  [anon_sym_jumptable] = anon_sym_jumptable,
  [anon_sym_jumpable__packed] = anon_sym_jumpable__packed,
  [anon_sym_constant] = anon_sym_constant,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_dup1] = anon_sym_dup1,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_swap1] = anon_sym_swap1,
  [anon_sym_calldataload] = anon_sym_calldataload,
  [anon_sym_shr] = anon_sym_shr,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_jumpi] = anon_sym_jumpi,
  [anon_sym_iszero] = anon_sym_iszero,
  [anon_sym_mstore] = anon_sym_mstore,
  [anon_sym_revert] = anon_sym_revert,
  [sym_number] = sym_number,
  [sym_hex_literal] = sym_hex_literal,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_interface_function] = sym_interface_function,
  [sym_interface_event] = sym_interface_event,
  [sym_solidity_parameter_list] = sym_solidity_parameter_list,
  [sym_solidity_parameter] = sym_solidity_parameter,
  [sym_preprocessor] = sym_preprocessor,
  [sym_parameters] = sym_parameters,
  [sym_parameter_usage] = sym_parameter_usage,
  [sym_macro_definition] = sym_macro_definition,
  [sym_macro_params] = sym_macro_params,
  [sym_macro_call] = sym_macro_call,
  [sym_jump_label_definition] = sym_jump_label_definition,
  [sym_jump_label_reference] = sym_jump_label_reference,
  [sym_block] = sym_block,
  [sym_table_definition] = sym_table_definition,
  [sym_constant_definition] = sym_constant_definition,
  [sym_constant_reference] = sym_constant_reference,
  [sym_opcode] = sym_opcode,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_interface_function_repeat1] = aux_sym_interface_function_repeat1,
  [aux_sym_solidity_parameter_list_repeat1] = aux_sym_solidity_parameter_list_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_macro_params_repeat1] = aux_sym_macro_params_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_table_definition_repeat1] = aux_sym_table_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDdefine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_event] = {
    .visible = true,
    .named = false,
  },
  [sym_solidity_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_memory] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_calldata] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_macro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_takes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jumptable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jumpable__packed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constant] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dup1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swap1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_calldataload] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jumpi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iszero] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mstore] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_revert] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_function] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_event] = {
    .visible = true,
    .named = true,
  },
  [sym_solidity_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_solidity_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_preprocessor] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_usage] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_params] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_call] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_label_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_table_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interface_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_solidity_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 5,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 12,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 110,
  [115] = 94,
  [116] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(127);
      ADVANCE_MAP(
        '"', 1,
        '#', 39,
        '(', 133,
        ')', 135,
        ',', 134,
        '/', 4,
        '0', 177,
        ':', 147,
        '<', 141,
        '=', 145,
        '>', 142,
        '[', 154,
        ']', 155,
        'a', 35,
        'c', 12,
        'd', 115,
        'e', 120,
        'f', 73,
        'i', 103,
        'j', 116,
        'm', 14,
        'n', 86,
        'p', 15,
        'r', 42,
        's', 58,
        't', 16,
        'v', 59,
        '{', 148,
        '}', 149,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(178);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(180);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(135);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(177);
      if (lookahead == '<') ADVANCE(141);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(178);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(135);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(190);
      if (lookahead == 'm') ADVANCE(199);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(235);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(234);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(85);
      if (lookahead == 'e') ADVANCE(120);
      if (lookahead == 'f') ADVANCE(73);
      if (lookahead == 'j') ADVANCE(119);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead == 't') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(178);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(156);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(160);
      END_STATE();
    case 10:
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '_') ADVANCE(95);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(70);
      if (lookahead == 's') ADVANCE(114);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(123);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(138);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(94);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(66);
      END_STATE();
    case 27:
      if (lookahead == 'b') ADVANCE(66);
      if (lookahead == 'k') ADVANCE(52);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(67);
      END_STATE();
    case 29:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 30:
      if (lookahead == 'b') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(98);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(111);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(158);
      END_STATE();
    case 37:
      if (lookahead == 'd') ADVANCE(165);
      END_STATE();
    case 38:
      if (lookahead == 'd') ADVANCE(152);
      END_STATE();
    case 39:
      if (lookahead == 'd') ADVANCE(43);
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 40:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(173);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(140);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(151);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 57:
      if (lookahead == 'f') ADVANCE(60);
      END_STATE();
    case 58:
      if (lookahead == 'h') ADVANCE(96);
      if (lookahead == 'w') ADVANCE(21);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(54);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(117);
      END_STATE();
    case 66:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 70:
      if (lookahead == 'm') ADVANCE(87);
      END_STATE();
    case 71:
      if (lookahead == 'm') ADVANCE(92);
      END_STATE();
    case 72:
      if (lookahead == 'm') ADVANCE(93);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(144);
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(129);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(105);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 83:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(171);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 86:
      if (lookahead == 'o') ADVANCE(77);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 88:
      if (lookahead == 'o') ADVANCE(102);
      END_STATE();
    case 89:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 90:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 91:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 92:
      if (lookahead == 'p') ADVANCE(167);
      END_STATE();
    case 93:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 94:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 95:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(163);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(122);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 99:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 101:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 103:
      if (lookahead == 's') ADVANCE(124);
      END_STATE();
    case 104:
      if (lookahead == 's') ADVANCE(146);
      END_STATE();
    case 105:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 106:
      if (lookahead == 's') ADVANCE(112);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(175);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(153);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(118);
      if (lookahead == 'v') ADVANCE(55);
      END_STATE();
    case 111:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 112:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 113:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 114:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 115:
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 116:
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 117:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 118:
      if (lookahead == 'u') ADVANCE(101);
      END_STATE();
    case 119:
      if (lookahead == 'u') ADVANCE(72);
      END_STATE();
    case 120:
      if (lookahead == 'v') ADVANCE(53);
      END_STATE();
    case 121:
      if (lookahead == 'w') ADVANCE(132);
      END_STATE();
    case 122:
      if (lookahead == 'y') ADVANCE(136);
      END_STATE();
    case 123:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 124:
      if (lookahead == 'z') ADVANCE(56);
      END_STATE();
    case 125:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(179);
      END_STATE();
    case 126:
      if (eof) ADVANCE(127);
      ADVANCE_MAP(
        '#', 39,
        '(', 133,
        '/', 4,
        '0', 177,
        ':', 147,
        '<', 141,
        '[', 154,
        'a', 191,
        'c', 183,
        'd', 228,
        'i', 222,
        'j', 229,
        'm', 223,
        'r', 197,
        's', 202,
        '}', 149,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(126);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(178);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_POUNDdefine);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_event);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_solidity_modifier);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_memory);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_memory);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_calldata);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_calldata);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_macro);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_takes);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_table);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_jumptable);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_jumpable__packed);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_constant);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_dup1);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_dup1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_swap1);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_swap1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_calldataload);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_shr);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_shr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_jump);
      if (lookahead == 'i') ADVANCE(169);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_jump);
      if (lookahead == 'i') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_jumpi);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_jumpi);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_iszero);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_iszero);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_mstore);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_mstore);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_revert);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_revert);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'x') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(178);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(178);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_hex_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(179);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(203);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(205);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(227);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(194);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(226);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(216);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(207);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(192);
      if (lookahead == 'n') ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(186);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(188);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(230);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(209);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(220);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(219);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(217);
      if (lookahead == 'w') ADVANCE(189);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(204);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(195);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(212);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(196);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(206);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(172);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(221);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(187);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(218);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(181);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(168);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(182);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(231);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(225);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(210);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(198);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(232);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(224);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(211);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(214);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(208);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(201);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'z') ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(233);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(233);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(235);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 126},
  [3] = {.lex_state = 126},
  [4] = {.lex_state = 126},
  [5] = {.lex_state = 126},
  [6] = {.lex_state = 126},
  [7] = {.lex_state = 126},
  [8] = {.lex_state = 126},
  [9] = {.lex_state = 126},
  [10] = {.lex_state = 126},
  [11] = {.lex_state = 126},
  [12] = {.lex_state = 126},
  [13] = {.lex_state = 126},
  [14] = {.lex_state = 126},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 7},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDdefine] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_event] = ACTIONS(1),
    [sym_solidity_modifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_memory] = ACTIONS(1),
    [anon_sym_calldata] = ACTIONS(1),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_macro] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_takes] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_table] = ACTIONS(1),
    [anon_sym_constant] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_dup1] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_swap1] = ACTIONS(1),
    [anon_sym_shr] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_jumpi] = ACTIONS(1),
    [anon_sym_iszero] = ACTIONS(1),
    [anon_sym_mstore] = ACTIONS(1),
    [anon_sym_revert] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym_definition] = STATE(17),
    [sym_preprocessor] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDdefine] = ACTIONS(7),
    [anon_sym_POUNDinclude] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      sym_hex_literal,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_comment,
    STATE(3), 8,
      sym_parameter_usage,
      sym_macro_call,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_constant_reference,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(19), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [45] = 9,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      sym_hex_literal,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      sym_comment,
    STATE(4), 8,
      sym_parameter_usage,
      sym_macro_call,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_constant_reference,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(19), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [90] = 9,
    ACTIONS(33), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      sym_number,
    ACTIONS(47), 1,
      sym_hex_literal,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_comment,
    STATE(4), 8,
      sym_parameter_usage,
      sym_macro_call,
      sym_jump_label_definition,
      sym_jump_label_reference,
      sym_constant_reference,
      sym_opcode,
      sym_literal,
      aux_sym_block_repeat1,
    ACTIONS(41), 11,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
  [135] = 2,
    ACTIONS(56), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(58), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [161] = 5,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_COLON,
    STATE(9), 1,
      sym_macro_params,
    ACTIONS(62), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(66), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [193] = 2,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(70), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [216] = 2,
    ACTIONS(72), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(74), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [239] = 2,
    ACTIONS(76), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(78), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [262] = 2,
    ACTIONS(80), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(82), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [285] = 2,
    ACTIONS(84), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(86), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [308] = 2,
    ACTIONS(88), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(90), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [331] = 2,
    ACTIONS(92), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(94), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [354] = 2,
    ACTIONS(96), 5,
      anon_sym_LT,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_comment,
    ACTIONS(98), 13,
      anon_sym_dup1,
      anon_sym_add,
      anon_sym_swap1,
      anon_sym_calldataload,
      anon_sym_shr,
      anon_sym_and,
      anon_sym_jump,
      anon_sym_jumpi,
      anon_sym_iszero,
      anon_sym_mstore,
      anon_sym_revert,
      sym_number,
      sym_identifier,
  [377] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_function,
    ACTIONS(102), 1,
      anon_sym_event,
    ACTIONS(108), 1,
      anon_sym_constant,
    ACTIONS(104), 2,
      anon_sym_macro,
      anon_sym_fn,
    ACTIONS(106), 3,
      anon_sym_table,
      anon_sym_jumptable,
      anon_sym_jumpable__packed,
    STATE(40), 5,
      sym_interface_function,
      sym_interface_event,
      sym_macro_definition,
      sym_table_definition,
      sym_constant_definition,
  [406] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    ACTIONS(112), 1,
      anon_sym_LT,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(116), 1,
      sym_hex_literal,
    ACTIONS(118), 1,
      sym_identifier,
    STATE(53), 2,
      sym_parameter_usage,
      sym_literal,
  [429] = 5,
    ACTIONS(7), 1,
      anon_sym_POUNDdefine,
    ACTIONS(9), 1,
      anon_sym_POUNDinclude,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 1,
      sym_comment,
    STATE(18), 3,
      sym_definition,
      sym_preprocessor,
      aux_sym_source_file_repeat1,
  [447] = 5,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      anon_sym_POUNDdefine,
    ACTIONS(129), 1,
      anon_sym_POUNDinclude,
    ACTIONS(132), 1,
      sym_comment,
    STATE(18), 3,
      sym_definition,
      sym_preprocessor,
      aux_sym_source_file_repeat1,
  [465] = 3,
    ACTIONS(137), 1,
      sym_solidity_modifier,
    STATE(19), 1,
      aux_sym_interface_function_repeat1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_returns,
      anon_sym_POUNDinclude,
      sym_comment,
  [479] = 4,
    ACTIONS(142), 1,
      anon_sym_returns,
    ACTIONS(144), 1,
      sym_solidity_modifier,
    STATE(21), 1,
      aux_sym_interface_function_repeat1,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [495] = 4,
    ACTIONS(148), 1,
      anon_sym_returns,
    ACTIONS(150), 1,
      sym_solidity_modifier,
    STATE(19), 1,
      aux_sym_interface_function_repeat1,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [511] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_LT,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(116), 1,
      sym_hex_literal,
    ACTIONS(152), 1,
      sym_identifier,
    STATE(64), 2,
      sym_parameter_usage,
      sym_literal,
  [531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(56), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_hex_literal,
  [544] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(116), 1,
      sym_hex_literal,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(25), 2,
      sym_literal,
      aux_sym_table_definition_repeat1,
  [561] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    ACTIONS(158), 1,
      sym_number,
    ACTIONS(161), 1,
      sym_hex_literal,
    STATE(25), 2,
      sym_literal,
      aux_sym_table_definition_repeat1,
  [578] = 2,
    ACTIONS(166), 1,
      sym_solidity_modifier,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_returns,
      anon_sym_POUNDinclude,
      sym_comment,
  [589] = 2,
    ACTIONS(170), 1,
      sym_solidity_modifier,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_returns,
      anon_sym_POUNDinclude,
      sym_comment,
  [600] = 2,
    ACTIONS(174), 1,
      sym_solidity_modifier,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_returns,
      anon_sym_POUNDinclude,
      sym_comment,
  [611] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(178), 2,
      anon_sym_memory,
      anon_sym_calldata,
  [626] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(116), 1,
      sym_hex_literal,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_literal,
      aux_sym_table_definition_repeat1,
  [643] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_returns,
    ACTIONS(186), 1,
      anon_sym_takes,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
  [659] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_returns,
    ACTIONS(192), 1,
      anon_sym_takes,
    STATE(46), 1,
      sym_block,
  [675] = 1,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(35), 1,
      sym_solidity_parameter,
  [695] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_solidity_parameter_list_repeat1,
  [708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_solidity_parameter_list_repeat1,
  [721] = 1,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [728] = 1,
    ACTIONS(211), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [735] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_parameters_repeat1,
  [748] = 1,
    ACTIONS(218), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_parameters_repeat1,
  [768] = 1,
    ACTIONS(224), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [775] = 1,
    ACTIONS(226), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [782] = 1,
    ACTIONS(228), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [789] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(86), 1,
      sym_parameters,
  [802] = 1,
    ACTIONS(234), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [809] = 1,
    ACTIONS(236), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_identifier,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [827] = 1,
    ACTIONS(242), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [834] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_returns,
    STATE(54), 1,
      sym_block,
  [847] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_solidity_parameter_list_repeat1,
  [860] = 1,
    ACTIONS(248), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [867] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_macro_params_repeat1,
  [880] = 1,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [887] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      sym_hex_literal,
    STATE(47), 1,
      sym_literal,
  [900] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_macro_params_repeat1,
  [913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    ACTIONS(258), 1,
      anon_sym_returns,
    STATE(60), 1,
      sym_block,
  [926] = 1,
    ACTIONS(260), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [933] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_macro_params_repeat1,
  [946] = 1,
    ACTIONS(267), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [953] = 1,
    ACTIONS(269), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [960] = 1,
    ACTIONS(271), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDdefine,
      anon_sym_POUNDinclude,
      sym_comment,
  [967] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_parameters_repeat1,
  [980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [988] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(76), 1,
      sym_solidity_parameter,
  [998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
  [1008] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_block,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1026] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_solidity_parameter_list,
  [1036] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(44), 1,
      sym_solidity_parameter_list,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1054] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_solidity_parameter_list,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_block,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1082] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym_block,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1100] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_solidity_parameter_list,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_number,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
  [1132] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_number,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_number,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_EQ,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_identifier,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
  [1174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_string,
  [1195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
  [1202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_number,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym_identifier,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_identifier,
  [1244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      sym_identifier,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_number,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_identifier,
  [1272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_LPAREN,
  [1279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_LPAREN,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_LPAREN,
  [1293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_LPAREN,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_number,
  [1314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [1321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
  [1328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [1335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
  [1349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_LBRACE,
  [1356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_EQ,
  [1363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_GT,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_identifier,
  [1377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 161,
  [SMALL_STATE(7)] = 193,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 239,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 285,
  [SMALL_STATE(12)] = 308,
  [SMALL_STATE(13)] = 331,
  [SMALL_STATE(14)] = 354,
  [SMALL_STATE(15)] = 377,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 429,
  [SMALL_STATE(18)] = 447,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 479,
  [SMALL_STATE(21)] = 495,
  [SMALL_STATE(22)] = 511,
  [SMALL_STATE(23)] = 531,
  [SMALL_STATE(24)] = 544,
  [SMALL_STATE(25)] = 561,
  [SMALL_STATE(26)] = 578,
  [SMALL_STATE(27)] = 589,
  [SMALL_STATE(28)] = 600,
  [SMALL_STATE(29)] = 611,
  [SMALL_STATE(30)] = 626,
  [SMALL_STATE(31)] = 643,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 675,
  [SMALL_STATE(34)] = 682,
  [SMALL_STATE(35)] = 695,
  [SMALL_STATE(36)] = 708,
  [SMALL_STATE(37)] = 721,
  [SMALL_STATE(38)] = 728,
  [SMALL_STATE(39)] = 735,
  [SMALL_STATE(40)] = 748,
  [SMALL_STATE(41)] = 755,
  [SMALL_STATE(42)] = 768,
  [SMALL_STATE(43)] = 775,
  [SMALL_STATE(44)] = 782,
  [SMALL_STATE(45)] = 789,
  [SMALL_STATE(46)] = 802,
  [SMALL_STATE(47)] = 809,
  [SMALL_STATE(48)] = 816,
  [SMALL_STATE(49)] = 827,
  [SMALL_STATE(50)] = 834,
  [SMALL_STATE(51)] = 847,
  [SMALL_STATE(52)] = 860,
  [SMALL_STATE(53)] = 867,
  [SMALL_STATE(54)] = 880,
  [SMALL_STATE(55)] = 887,
  [SMALL_STATE(56)] = 900,
  [SMALL_STATE(57)] = 913,
  [SMALL_STATE(58)] = 926,
  [SMALL_STATE(59)] = 933,
  [SMALL_STATE(60)] = 946,
  [SMALL_STATE(61)] = 953,
  [SMALL_STATE(62)] = 960,
  [SMALL_STATE(63)] = 967,
  [SMALL_STATE(64)] = 980,
  [SMALL_STATE(65)] = 988,
  [SMALL_STATE(66)] = 998,
  [SMALL_STATE(67)] = 1008,
  [SMALL_STATE(68)] = 1018,
  [SMALL_STATE(69)] = 1026,
  [SMALL_STATE(70)] = 1036,
  [SMALL_STATE(71)] = 1046,
  [SMALL_STATE(72)] = 1054,
  [SMALL_STATE(73)] = 1064,
  [SMALL_STATE(74)] = 1074,
  [SMALL_STATE(75)] = 1082,
  [SMALL_STATE(76)] = 1092,
  [SMALL_STATE(77)] = 1100,
  [SMALL_STATE(78)] = 1110,
  [SMALL_STATE(79)] = 1118,
  [SMALL_STATE(80)] = 1125,
  [SMALL_STATE(81)] = 1132,
  [SMALL_STATE(82)] = 1139,
  [SMALL_STATE(83)] = 1146,
  [SMALL_STATE(84)] = 1153,
  [SMALL_STATE(85)] = 1160,
  [SMALL_STATE(86)] = 1167,
  [SMALL_STATE(87)] = 1174,
  [SMALL_STATE(88)] = 1181,
  [SMALL_STATE(89)] = 1188,
  [SMALL_STATE(90)] = 1195,
  [SMALL_STATE(91)] = 1202,
  [SMALL_STATE(92)] = 1209,
  [SMALL_STATE(93)] = 1216,
  [SMALL_STATE(94)] = 1223,
  [SMALL_STATE(95)] = 1230,
  [SMALL_STATE(96)] = 1237,
  [SMALL_STATE(97)] = 1244,
  [SMALL_STATE(98)] = 1251,
  [SMALL_STATE(99)] = 1258,
  [SMALL_STATE(100)] = 1265,
  [SMALL_STATE(101)] = 1272,
  [SMALL_STATE(102)] = 1279,
  [SMALL_STATE(103)] = 1286,
  [SMALL_STATE(104)] = 1293,
  [SMALL_STATE(105)] = 1300,
  [SMALL_STATE(106)] = 1307,
  [SMALL_STATE(107)] = 1314,
  [SMALL_STATE(108)] = 1321,
  [SMALL_STATE(109)] = 1328,
  [SMALL_STATE(110)] = 1335,
  [SMALL_STATE(111)] = 1342,
  [SMALL_STATE(112)] = 1349,
  [SMALL_STATE(113)] = 1356,
  [SMALL_STATE(114)] = 1363,
  [SMALL_STATE(115)] = 1370,
  [SMALL_STATE(116)] = 1377,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_label_reference, 1, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_label_reference, 1, 0, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_params, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_params, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcode, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcode, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 2, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 2, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_params, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_params, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_label_definition, 2, 0, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_label_definition, 2, 0, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_usage, 3, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_usage, 3, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_reference, 3, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_reference, 3, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_params, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_params, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interface_function_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interface_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_function, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_function, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter_list, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_parameter_list, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter_list, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_parameter_list, 4, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter_list, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_solidity_parameter_list, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_solidity_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_solidity_parameter_list_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_function, 6, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 6, 0, 1),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 4, 0, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_event, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 7, 0, 1),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_definition, 4, 0, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_function, 5, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 10, 0, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 5, 0, 1),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_params_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_params_repeat1, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 11, 0, 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 14, 0, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 15, 0, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solidity_parameter, 3, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [295] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_huff(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "huff",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
